BoxLayout:
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.2
        Button:
            text: 'Greet'
            on_press: app.handle_greet()
        Button:
            text: 'Clear'
            on_press: app.handle_clear()
    BoxLayout:
        orientation: 'vertical'
        TextInput:
            id: input_name
            text: ''
        Label:
            id: output_label
            text: 'Enter your name'
            color: (1, 1, 0, 1)
